services:
    tekana-e-wallet-api:
        build: .
        container_name: tekana-e-wallet-api
        environment:
            PORT: ${PORT}
            DATABASE_URL: ${DATABASE_URL}
            JWT_SECRET: ${JWT_SECRET}
        depends_on:
            - psqldb
        ports:
            - 4000:${PORT}
        restart: unless-stopped
        networks:
            - tekana-net

    psqldb:
        image: postgres:14-alpine
        container_name: psqldb
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - psqldb:/var/lib/postgresql/data
        networks:
            - tekana-net
volumes:
    psqldb:
networks:
    tekana-net: